### PR TITLE
Use PINRemoteImage to manage remote images

### LINKED ISSUE #130: Decoding images on main thread causes animation stutters
The current way we do images has a few drawbacks:

- Calling `Data(contentsOf: url)` is synchronous, so it ties up a system thread waiting for the data to come back.
- Duplicate calls at the same time are not de-duped.
- **Most importantly, images are not decoded from WebP to bitmap off-thread, so they get decoded on the main thread causing animation stutters.**

In this profile of scrolling down 4 or 5 pages on the home screen, notice the 3 seconds of main thread time, and the fact that the heaviest stack trace is Core Animation decoding the WebP images on main for display.

Screen Shot 2021-05-22 at 7 18 19 AM

### PR DESCRIPTION
**Pull request by Adlai-Holler**
Fixes #130 

PINRemoteImage is a pretty good framework for handling all of the above. It also supports animated images and a disk cache.

Test on my iPhone 11 Pro. Scroll down 4 or 5 pages on home, then scroll back to the top. Notice the main thread time drops from 3 seconds in the "before" trace from the issue, to 2 seconds, with no image decoding on main.

Screen Shot 2021-05-22 at 7 21 46 AM

### CODE REVIEW

File: Odysee/Utils/Cache.swift [hunk 1]
```diff
@@ -7,13 +7,14 @@
 
 import Foundation
 
+// TODO: Remove in favor of PINRemoteImage.
 class Cache {
```
Comment (akinwale) [inline Odysee/Utils/Cache.swift:11]: Looking at the changes, it appears this class is no longer needed.

**Review by akinwale — APPROVED** [review]
Looks good. Thanks!
